#line 1 "3rd/iec61131.l.cpp"

#line 3 "3rd/iec61131.l.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer deci_FlexLexer

#define yyalloc deci_alloc
    #define yyrealloc deci_realloc
    #define yyfree deci_free

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */
#include <iostream>
#include <errno.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
/* end standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{

	std::streambuf* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>

int yyFlexLexer::yywrap() { return 1; }
int yyFlexLexer::yylex()
	{
	LexerError( "yyFlexLexer::yylex invoked but %option yyclass used" );
	return 0;
	}

#define YY_DECL int deci_scanner_t::yylex()

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 69
#define YY_END_OF_BUFFER 70
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[208] =
    {   0,
        0,    0,    0,    0,    0,    0,   70,   68,   67,   66,
       35,   52,   51,   48,   46,   49,   47,   50,   65,   45,
       43,   39,   36,   38,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   54,   53,   68,   32,   34,    4,    3,    4,    8,
        7,    8,    5,   42,    1,    9,    0,   64,   65,   44,
       41,   37,   40,    0,   62,   62,   62,    0,   62,   62,
       19,   62,   62,   20,   62,   62,   62,   62,   62,   22,
       62,   62,   62,   29,   55,   32,   62,   62,   62,   18,
       62,   62,   62,   62,   62,   62,   62,   62,    2,    6,

        9,   63,   64,   62,    0,   35,    0,   62,   62,   62,
       62,   62,   62,   62,   62,   17,   62,   33,   34,   56,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   31,   63,    0,   62,    0,   62,    0,   62,   62,
       28,   62,   26,   62,   62,   10,   62,    0,   62,   62,
       62,   62,   23,   57,   62,   62,   62,   62,   62,   63,
        0,   62,    0,    0,   62,   25,   62,   62,   62,   62,
       62,   58,    0,   61,   62,   62,   62,   15,   62,   12,
        0,   62,   59,   60,   24,   62,   62,   27,   62,   62,
       61,   61,   14,   11,    0,   62,   21,   62,   62,   61,

       30,   62,   62,   62,   13,   16,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    1,    1,    5,    1,    6,
        7,    8,    9,   10,   11,   12,   13,   14,   15,   16,
       16,   16,   16,   16,   16,   16,   16,   17,   18,   19,
       20,   21,    1,    1,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   28,   28,   31,   32,   33,   34,   35,
       28,   36,   37,   38,   39,   28,   40,   41,   42,   28,
       43,    1,   44,    1,   45,    1,   46,   47,   48,   49,

       50,   51,   28,   52,   53,   28,   28,   54,   55,   56,
       57,   58,   28,   59,   60,   61,   62,   28,   63,   64,
       65,   28,    1,   66,    1,   67,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[68] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    1,    4,    4,    4,    1,    1,    1,    1,
        1,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    6,    1,    7,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    1,    1
    } ;

static const flex_int16_t yy_base[218] =
    {   0,
        0,    0,   65,   66,   67,   68,  150, 1072, 1072, 1072,
     1072,  141, 1072,  125, 1072, 1072, 1072,   64,   74,  108,
     1072,   59, 1072,  107,   69,   79,   74,   73,  101,   95,
      106,  134,  112,  117,  145,  158,  163,  177,  218,  180,
      161, 1072, 1072,    0, 1072, 1072, 1072, 1072,  110, 1072,
     1072,  112, 1072, 1072, 1072,    0,    0,   83,  242, 1072,
     1072, 1072, 1072,   73,  196,  205,  238,   90,  182,  231,
      234,  247,  252,  235,  256,  276,  281,  288,  290,  263,
      293,  314,  323,  309,  272,  310,  347,  344,  357,  330,
      364,  360,  377,  382,  393,  398,  402,  403, 1072, 1072,

        0,   47,   95,  102,  438,  407,  455,  221,  443,  452,
      446,  480,  447,  481,  456,  484,  497,  486,  490,  493,
      522,  510,  527,  536,  538,  531,  549,  566,  556,  577,
      584,  565,   42,    0,  119,  621,  130,  629,  605,  598,
      582,  624,  622,  619,  678,  617,  646,  683,  667,  673,
      626,  700,  678,  683,  711,  702,  716,  718,  735,   37,
      772,  143,  775,   86,  767,  763,  780,  764,  783,  773,
      802,  770,  748,  827,  813,  816,  829,  818,  842,  822,
      874, 1072, 1072, 1072,  835,  859,  861,  864,  870,  880,
      916,  924,  900,  907,  932,  917,  916,  918,  935,  939,

      928,  956,  953,  963,  929,  954, 1072, 1028, 1035, 1040,
     1044, 1049, 1053, 1054, 1058, 1062, 1066
    } ;

static const flex_int16_t yy_def[218] =
    {   0,
      207,    1,  208,  208,  209,  209,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  210,  210,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,  207,  207,  211,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  212,  213,  207,  207,  207,
      207,  207,  207,  214,   26,   26,   26,  207,  210,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,  207,  207,

      212,  215,  207,  216,  214,   26,  207,  207,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,  215,  217,  216,  207,  216,  207,  207,   26,
       26,   26,   26,   26,  210,   26,   26,  207,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,  217,
      207,  207,  207,  207,   26,   26,   26,   26,   26,   26,
       26,   26,  207,  207,   26,   26,   26,   26,   26,   26,
      207,  207,  207,  207,   26,   26,   26,   26,   26,   26,
      207,  207,   26,   26,  207,   26,   26,   26,   26,  207,

       26,   26,   26,   26,   26,   26,    0,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207
    } ;

static const flex_int16_t yy_nxt[1140] =
    {   0,
        8,    9,   10,    8,   11,   12,   13,   14,   15,   16,
       17,    8,   18,   19,   19,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   31,   32,
       31,   33,   34,   35,   31,   36,   37,   38,   39,   40,
       41,   31,   42,   43,   44,   25,   26,   27,   28,   29,
       30,   31,   32,   31,   33,   34,   35,   31,   36,   37,
       38,   39,   40,   41,   31,   45,   46,   48,   48,   51,
       51,   55,   49,   49,   52,   52,   56,   57,   61,   62,
       64,  134,   65,   65,   65,   58,  134,   59,   59,   59,
       64,  134,   65,   65,   65,   72,  103,  103,  103,  183,

      184,   67,   73,  107,  107,  107,   74,   66,  103,  103,
      103,   68,   70,   69,   66,   66,   78,  105,  100,   72,
       71,   68,   99,   69,   67,   73,   63,   60,   79,   74,
       66,   75,   54,   76,   66,   70,   66,   66,   66,   66,
       78,   77,   66,   71,  136,   82,  137,   66,   53,  207,
       83,   79,  207,   66,   75,  207,   76,   66,   66,   66,
       80,  136,   66,  137,   77,   66,   81,   66,   82,  207,
       66,   84,  136,   83,  162,   66,   66,   85,   66,  207,
       86,   66,  207,   87,   80,  136,   66,  162,  207,   81,
       66,   66,   88,   64,   97,   84,   66,  207,   66,   66,

       85,   66,   66,   86,   66,   89,  207,   87,   96,   66,
       90,  207,   91,   66,   66,   88,  207,   97,   66,   66,
      207,   66,   66,  207,   68,   66,  108,   66,   89,   66,
      207,   96,   64,   90,  207,   91,   66,   66,   66,  207,
      207,   66,   92,  207,   66,   57,   66,   93,  207,  207,
       94,   66,   66,   58,   95,   59,   59,   59,  207,   66,
       66,   66,  106,   68,  109,  108,   92,   66,   66,   66,
       93,   66,   66,   94,   66,   66,   66,   95,  207,   66,
       66,  207,   66,  110,  111,   66,  106,  109,   66,   66,
       66,   66,  112,   66,   66,   66,   66,   66,   66,   66,

      113,  207,   66,   66,   66,   66,  110,  111,   66,   66,
      114,   66,   66,   66,   66,  112,   66,   66,  115,   66,
       66,   66,   66,   66,  113,  116,   66,   66,   66,   66,
      117,   66,   66,  114,   66,  120,   66,   66,  118,  207,
       66,  115,   66,   66,   66,   66,   66,   66,  116,   66,
       66,   66,   66,  117,   66,   66,   66,   66,  207,  120,
      119,  207,  118,   66,   66,   66,   66,  207,  121,  207,
       66,   66,  207,   66,   66,  207,  124,   66,   66,   66,
       66,  122,  125,  119,  123,   66,   66,   66,   66,  127,
       66,  207,  121,   66,   66,  207,  207,   66,   66,  124,

       66,   66,  126,   66,  122,   66,  125,  123,   66,  128,
       66,   66,  127,   66,  207,   66,   66,  207,   66,  129,
       66,   66,  130,   66,   66,  126,   66,  131,   66,  207,
      207,   66,  128,   66,   66,   66,   66,  132,   66,   66,
       66,   66,  129,   66,   66,  130,   66,  207,   66,   66,
      131,  104,  104,  104,   66,  207,  207,   66,   66,   66,
      132,  207,   66,   66,  138,  207,   66,   66,  107,  107,
      107,   66,  207,  140,  207,  207,   66,  141,  207,   66,
       66,  207,  207,  142,   66,   66,  207,   66,   66,   66,
      207,  145,  147,   66,  207,  207,  140,   66,  139,   66,

      148,  141,   66,   66,  207,  143,  142,   66,   66,  144,
       66,   66,   66,   66,   66,  147,   66,   66,  146,   66,
       66,   66,   66,   66,  207,   66,   66,   66,  207,  143,
       66,   66,  144,  207,   66,  150,   66,   66,   66,  207,
       66,  146,   66,   66,   66,   66,   66,  207,   66,   66,
       66,   66,  149,   66,   66,   66,  154,   66,  207,  150,
       66,   66,  207,   66,   66,  151,   66,  207,   66,   66,
      153,   66,   66,  152,   66,  149,  207,   66,   66,   66,
      154,  155,   66,   66,  207,  157,   66,   66,  151,   66,
       66,   66,   66,  153,   66,   66,  152,   66,   66,   66,

       66,  164,   66,  156,  155,   66,   66,   66,  157,  158,
       66,  207,   66,   66,  159,   66,   64,   66,   66,  207,
       66,   66,   66,   66,  207,   66,  156,  148,  207,   66,
       66,   66,  158,   66,  161,  161,  161,  159,   66,   66,
       66,   66,  163,  163,  163,  166,   66,  136,   66,  162,
       66,  165,   66,  207,   66,   66,  207,   66,   66,   66,
       66,  176,   66,   66,  207,   66,  207,   66,  207,  166,
      148,  172,  207,   66,  165,   66,  207,  207,   66,   66,
       66,   66,   66,   66,  176,  207,   66,   66,   66,   64,
       66,  173,  207,  173,  175,  172,  174,  174,  174,  207,

       66,  167,   66,  148,  168,  148,   66,  169,   66,  207,
       66,   66,  207,  170,   66,  207,   66,  171,  175,   66,
       68,  207,  108,   66,   66,  167,  207,  207,  168,   66,
      169,   66,  207,   66,   66,   66,  170,   66,  207,   66,
      171,   66,   66,   66,   66,  207,  178,   66,  177,   66,
      207,   66,   66,  207,  207,  179,   66,   66,   66,   66,
      180,  174,  174,  174,   66,  207,   66,   66,   66,  178,
      207,  177,   66,  207,   66,   66,   66,  207,  179,  207,
       66,  181,   66,  207,  180,  161,  161,  161,  163,  163,
      163,   66,  207,  185,  207,  207,   66,  187,  189,   66,

       66,  186,  207,   66,   66,   66,   66,  207,   66,  188,
      207,   66,  207,   66,   66,  182,   66,  185,  139,   66,
      187,   66,  189,   66,   66,  186,   66,   66,   66,   66,
      190,   66,  148,  188,   66,   66,   66,   66,  191,   66,
      192,  192,  192,   66,   66,  148,   66,   66,  194,   66,
      193,   66,  207,  190,   66,   66,  207,   66,   66,   66,
      207,  207,   66,   66,  207,  207,   66,  207,   66,   66,
       66,  194,   66,  193,   66,   66,   66,   66,   66,  207,
       66,  207,   66,   66,  207,   66,   66,  195,  195,  195,
      207,   66,   66,   66,   66,  196,  197,   66,   66,   66,

       66,  207,   66,   66,  198,   66,   66,  207,  207,  199,
      207,   66,  207,   66,  207,   66,  207,   66,  196,  197,
       66,   66,  207,   66,  207,   66,   66,  198,   66,  200,
      200,  200,  199,   66,   66,  191,   66,  192,  192,  192,
       66,   66,  201,  202,   66,  195,  195,  195,   66,   66,
       66,   66,  200,  200,  200,  207,   66,   66,   66,   66,
      207,   66,   66,   66,   66,  203,  201,  202,   66,   66,
       66,   66,   66,   66,   66,  182,   66,  204,  205,  207,
       66,   66,   66,  207,   66,   66,   66,   66,  203,   66,
      207,   66,   66,   66,   66,   66,   66,   66,  207,   66,

      206,  204,  205,  207,   66,  207,  207,  207,  207,   66,
       66,  207,   66,  207,  207,  207,  207,   66,   66,   66,
       66,  207,  207,  206,  207,  207,  207,   66,   47,   47,
       47,   47,   47,   47,   47,   50,   50,   50,   50,   50,
       50,   50,   66,   66,   66,   66,   66,   98,   98,  101,
      207,  101,  101,  101,  101,  101,  102,  102,  104,  207,
      104,  133,  133,  207,  133,  135,  135,  135,  135,  160,
      160,    7,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,

      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207
    } ;

static const flex_int16_t yy_chk[1140] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    4,    5,
        6,   18,    3,    4,    5,    6,   18,   19,   22,   22,
       25,  160,   25,   25,   25,   19,  133,   19,   19,   19,
       26,  102,   26,   26,   26,   27,   58,   58,   58,  164,

      164,   25,   28,   68,   68,   68,   28,   27,  103,  103,
      103,   25,   26,   25,   28,   27,   30,   64,   52,   27,
       26,   26,   49,   26,   25,   28,   24,   20,   30,   28,
       27,   29,   14,   29,   29,   26,   30,   28,   27,   31,
       30,   29,   29,   26,  104,   33,  104,   31,   12,    7,
       34,   30,    0,   33,   29,    0,   29,   29,   34,   30,
       32,  135,   31,  135,   29,   29,   32,   32,   33,    0,
       31,   35,  137,   34,  137,   32,   33,   35,   35,    0,
       35,   34,    0,   36,   32,  162,   35,  162,    0,   32,
       32,   36,   37,   69,   41,   35,   37,    0,   32,   36,

       35,   35,   41,   35,   37,   38,    0,   36,   40,   35,
       38,    0,   38,   40,   36,   37,    0,   41,   38,   37,
        0,   40,   36,    0,   69,   41,   69,   37,   38,   65,
        0,   40,  108,   38,    0,   38,   40,   65,   66,    0,
        0,   38,   39,    0,   40,   59,   66,   39,    0,    0,
       39,   39,   65,   59,   39,   59,   59,   59,    0,   39,
       65,   66,   67,  108,   70,  108,   39,   71,   74,   66,
       39,   67,   70,   39,   39,   71,   74,   39,    0,   67,
       72,    0,   39,   72,   73,   73,   67,   70,   72,   75,
       71,   74,   75,   73,   67,   70,   80,   75,   71,   74,

       76,    0,   67,   72,   80,   85,   72,   73,   73,   76,
       77,   72,   75,   85,   77,   75,   73,   76,   78,   80,
       75,   78,   77,   79,   76,   79,   81,   80,   85,   78,
       81,   79,   76,   77,   81,   84,   85,   77,   82,    0,
       76,   78,   84,   86,   78,   77,   79,   82,   79,   81,
       84,   86,   78,   81,   79,   82,   83,   81,    0,   84,
       83,    0,   82,   90,   83,   84,   86,    0,   87,    0,
       82,   90,    0,   84,   86,    0,   88,   88,   82,   83,
       87,   87,   89,   83,   87,   88,   90,   83,   87,   92,
       89,    0,   87,   92,   90,    0,    0,   91,   89,   88,

       88,   92,   91,   87,   87,   91,   89,   87,   88,   93,
       93,   87,   92,   89,    0,   94,   92,    0,   93,   94,
       91,   89,   95,   94,   92,   91,   95,   96,   91,    0,
        0,   96,   93,   93,   95,   97,   98,   97,   94,   96,
      106,   93,   94,   97,   98,   95,   94,    0,  106,   95,
       96,  105,  105,  105,   96,    0,    0,   95,   97,   98,
       97,    0,   96,  106,  107,    0,   97,   98,  107,  107,
      107,  106,    0,  109,    0,    0,  109,  110,    0,  111,
      113,    0,  105,  111,  109,  110,    0,  111,  113,  115,
        0,  113,  115,  110,    0,    0,  109,  115,  107,  109,

      117,  110,  111,  113,    0,  112,  111,  109,  110,  112,
      111,  113,  115,  112,  114,  115,  110,  116,  114,  118,
      115,  112,  114,  119,    0,  116,  120,  118,    0,  112,
      117,  119,  112,    0,  120,  122,  112,  114,  117,    0,
      116,  114,  118,  122,  112,  114,  119,    0,  116,  120,
      118,  122,  121,  117,  119,  121,  126,  120,    0,  122,
      123,  117,    0,  121,  126,  123,  122,    0,  123,  124,
      125,  125,  126,  124,  122,  121,    0,  124,  121,  125,
      126,  127,  127,  123,    0,  129,  121,  126,  123,  129,
      127,  123,  124,  125,  125,  126,  124,  129,  132,  128,

      124,  140,  125,  128,  127,  127,  132,  128,  129,  130,
      130,    0,  129,  127,  131,  141,  139,  131,  130,    0,
      129,  132,  128,  141,    0,  131,  128,  142,    0,  132,
      128,  140,  130,  130,  136,  136,  136,  131,  141,  140,
      131,  130,  138,  138,  138,  144,  141,  139,  131,  139,
      146,  143,  144,    0,  140,  143,    0,  142,  146,  151,
      144,  151,  140,  143,    0,  142,    0,  151,    0,  144,
      149,  147,    0,  146,  143,  144,    0,    0,  143,  147,
      142,  146,  151,  144,  151,    0,  143,  147,  142,  145,
      151,  148,    0,  148,  150,  147,  148,  148,  148,    0,

      149,  145,  147,  152,  145,  156,  150,  145,  149,    0,
      147,  153,    0,  145,  150,    0,  154,  145,  150,  153,
      145,    0,  145,  149,  154,  145,    0,    0,  145,  150,
      145,  149,    0,  152,  153,  156,  145,  150,    0,  154,
      145,  152,  153,  156,  155,    0,  157,  154,  155,  157,
        0,  158,  155,    0,    0,  158,  152,  157,  156,  158,
      159,  173,  173,  173,  152,    0,  156,  155,  159,  157,
        0,  155,  157,    0,  158,  155,  159,    0,  158,    0,
      157,  161,  158,    0,  159,  161,  161,  161,  163,  163,
      163,  159,    0,  165,    0,    0,  166,  168,  170,  159,

      165,  167,    0,  172,  166,  168,  170,    0,  165,  169,
        0,  172,    0,  167,  170,  161,  169,  165,  163,  166,
      168,  167,  170,  165,  169,  167,  172,  166,  168,  170,
      171,  165,  177,  169,  172,  171,  167,  170,  174,  169,
      174,  174,  174,  171,  167,  179,  175,  169,  176,  176,
      175,  178,    0,  171,  175,  180,    0,  176,  171,  178,
        0,    0,  177,  180,    0,    0,  171,    0,  185,  175,
      177,  176,  176,  175,  178,  179,  185,  175,  180,    0,
      176,    0,  178,  179,    0,  177,  180,  181,  181,  181,
        0,  185,  186,  177,  187,  186,  187,  188,  179,  185,

      186,    0,  187,  189,  189,  188,  179,    0,    0,  190,
        0,  189,    0,  190,    0,  186,    0,  187,  186,  187,
      188,  190,    0,  186,    0,  187,  189,  189,  188,  191,
      191,  191,  190,  193,  189,  192,  190,  192,  192,  192,
      194,  193,  196,  198,  190,  195,  195,  195,  194,  197,
      196,  198,  200,  200,  200,    0,  193,  197,  196,  198,
        0,  201,  205,  194,  193,  199,  196,  198,  199,  201,
      205,  194,  197,  196,  198,  195,  199,  202,  203,    0,
      197,  196,  198,    0,  201,  205,  203,  206,  199,  202,
        0,  199,  201,  205,  203,  206,  204,  202,    0,  199,

      204,  202,  203,    0,  204,    0,    0,    0,    0,  203,
      206,    0,  202,    0,    0,    0,    0,  203,  206,  204,
      202,    0,    0,  204,    0,    0,    0,  204,  208,  208,
      208,  208,  208,  208,  208,  209,  209,  209,  209,  209,
      209,  209,  210,  210,  210,  210,  210,  211,  211,  212,
        0,  212,  212,  212,  212,  212,  213,  213,  214,    0,
      214,  215,  215,    0,  215,  216,  216,  216,  216,  217,
      217,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,

      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[70] =
    {   0,
0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 1, 0, 0, 0,     };

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "3rd/iec61131.l"
#line 2 "3rd/iec61131.l"
    #include <deci.hpp>
    #include <deci/scanner_t.hpp>
    #include "iec61131.y.hpp"
    
    #define YY_NO_UNISTD_H
    #define yyterminate() return deci::parser_t::make_END();
    #define YY_USER_ACTION this->cloc.step(); this->cloc.columns(yyleng); 
    #define DEFAULT_LOCATION_ARGUMENT this->cloc
#line 765 "3rd/iec61131.l.cpp"

#line 767 "3rd/iec61131.l.cpp"

#define INITIAL 0
#define DIV_COMMENTS 1
#define BRACE_COMMENTS 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
\
	if ( (int)(result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
#define YY_DECL int yyFlexLexer::yylex()
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin.rdbuf(std::cin.rdbuf());

		if ( ! yyout )
			yyout.rdbuf(std::cout.rdbuf());

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 37 "3rd/iec61131.l"


#line 904 "3rd/iec61131.l.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 208 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1072 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 39 "3rd/iec61131.l"
{ BEGIN(DIV_COMMENTS); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 40 "3rd/iec61131.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 41 "3rd/iec61131.l"
{ this->cloc.lines(); this->cloc.step(); /* Ingnore multiline comments */ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 42 "3rd/iec61131.l"
{ /* Ingnore multiline comments */ }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 44 "3rd/iec61131.l"
{ BEGIN(BRACE_COMMENTS); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 45 "3rd/iec61131.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 46 "3rd/iec61131.l"
{ this->cloc.lines(); this->cloc.step(); /* Ingnore multiline comments */ }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 47 "3rd/iec61131.l"
{ /* Ingnore multiline comments */ }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 49 "3rd/iec61131.l"
{ /* Ignore single line comments */ }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 51 "3rd/iec61131.l"
{ return deci::parser_t::make_EXIT(DEFAULT_LOCATION_ARGUMENT);           }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 52 "3rd/iec61131.l"
{ return deci::parser_t::make_RETURN(DEFAULT_LOCATION_ARGUMENT);         }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 53 "3rd/iec61131.l"
{ return deci::parser_t::make_WHILE(DEFAULT_LOCATION_ARGUMENT);          }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 54 "3rd/iec61131.l"
{ return deci::parser_t::make_END_WHILE(DEFAULT_LOCATION_ARGUMENT);      }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 55 "3rd/iec61131.l"
{ return deci::parser_t::make_REPEAT(DEFAULT_LOCATION_ARGUMENT);         }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 56 "3rd/iec61131.l"
{ return deci::parser_t::make_UNTIL(DEFAULT_LOCATION_ARGUMENT);          }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 57 "3rd/iec61131.l"
{ return deci::parser_t::make_END_REPEAT(DEFAULT_LOCATION_ARGUMENT);     }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 58 "3rd/iec61131.l"
{ return deci::parser_t::make_FOR(DEFAULT_LOCATION_ARGUMENT);            }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 59 "3rd/iec61131.l"
{ return deci::parser_t::make_TO(DEFAULT_LOCATION_ARGUMENT);             }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 60 "3rd/iec61131.l"
{ return deci::parser_t::make_BY(DEFAULT_LOCATION_ARGUMENT);             }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 61 "3rd/iec61131.l"
{ return deci::parser_t::make_DO(DEFAULT_LOCATION_ARGUMENT);             }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 62 "3rd/iec61131.l"
{ return deci::parser_t::make_END_FOR(DEFAULT_LOCATION_ARGUMENT);        }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 63 "3rd/iec61131.l"
{ return deci::parser_t::make_IF(DEFAULT_LOCATION_ARGUMENT);             }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 64 "3rd/iec61131.l"
{ return deci::parser_t::make_THEN(DEFAULT_LOCATION_ARGUMENT);           }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 65 "3rd/iec61131.l"
{ return deci::parser_t::make_ELSEIF(DEFAULT_LOCATION_ARGUMENT);         }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 66 "3rd/iec61131.l"
{ return deci::parser_t::make_ELSIF(DEFAULT_LOCATION_ARGUMENT);          }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 67 "3rd/iec61131.l"
{ return deci::parser_t::make_ELSE(DEFAULT_LOCATION_ARGUMENT);           }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 68 "3rd/iec61131.l"
{ return deci::parser_t::make_END_IF(DEFAULT_LOCATION_ARGUMENT);         }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 69 "3rd/iec61131.l"
{ return deci::parser_t::make_CASE(DEFAULT_LOCATION_ARGUMENT);           }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 70 "3rd/iec61131.l"
{ return deci::parser_t::make_OF(DEFAULT_LOCATION_ARGUMENT);             }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 71 "3rd/iec61131.l"
{ return deci::parser_t::make_END_CASE(DEFAULT_LOCATION_ARGUMENT);       }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 72 "3rd/iec61131.l"
{ return deci::parser_t::make_XOR(DEFAULT_LOCATION_ARGUMENT);            }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 73 "3rd/iec61131.l"
{ return deci::parser_t::make_OR(DEFAULT_LOCATION_ARGUMENT);             }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 74 "3rd/iec61131.l"
{ return deci::parser_t::make_MOD(DEFAULT_LOCATION_ARGUMENT);            }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 75 "3rd/iec61131.l"
{ return deci::parser_t::make_NOT(DEFAULT_LOCATION_ARGUMENT);            }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 76 "3rd/iec61131.l"
{ return deci::parser_t::make_AND(DEFAULT_LOCATION_ARGUMENT);            }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 77 "3rd/iec61131.l"
{ return deci::parser_t::make_EQU(DEFAULT_LOCATION_ARGUMENT);            }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 78 "3rd/iec61131.l"
{ return deci::parser_t::make_NEQU(DEFAULT_LOCATION_ARGUMENT);           }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 79 "3rd/iec61131.l"
{ return deci::parser_t::make_GR(DEFAULT_LOCATION_ARGUMENT);             }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 80 "3rd/iec61131.l"
{ return deci::parser_t::make_LS(DEFAULT_LOCATION_ARGUMENT);             }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 81 "3rd/iec61131.l"
{ return deci::parser_t::make_GE(DEFAULT_LOCATION_ARGUMENT);             }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 82 "3rd/iec61131.l"
{ return deci::parser_t::make_LE(DEFAULT_LOCATION_ARGUMENT);             }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 83 "3rd/iec61131.l"
{ return deci::parser_t::make_POW(DEFAULT_LOCATION_ARGUMENT);            }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 84 "3rd/iec61131.l"
{ return deci::parser_t::make_ST_END(DEFAULT_LOCATION_ARGUMENT);         }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 85 "3rd/iec61131.l"
{ return deci::parser_t::make_ASSIGN(DEFAULT_LOCATION_ARGUMENT);         }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 86 "3rd/iec61131.l"
{ return deci::parser_t::make_COLON(DEFAULT_LOCATION_ARGUMENT);          }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 87 "3rd/iec61131.l"
{ return deci::parser_t::make_SUM(DEFAULT_LOCATION_ARGUMENT);            }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 88 "3rd/iec61131.l"
{ return deci::parser_t::make_SUB(DEFAULT_LOCATION_ARGUMENT);            }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 89 "3rd/iec61131.l"
{ return deci::parser_t::make_MUL(DEFAULT_LOCATION_ARGUMENT);            }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 90 "3rd/iec61131.l"
{ return deci::parser_t::make_COMMA(DEFAULT_LOCATION_ARGUMENT);          }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 91 "3rd/iec61131.l"
{ return deci::parser_t::make_DIV(DEFAULT_LOCATION_ARGUMENT);            }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 92 "3rd/iec61131.l"
{ return deci::parser_t::make_BCLOSE(DEFAULT_LOCATION_ARGUMENT);         }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 93 "3rd/iec61131.l"
{ return deci::parser_t::make_BOPEN(DEFAULT_LOCATION_ARGUMENT);          }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 94 "3rd/iec61131.l"
{ return deci::parser_t::make_CCLOSE(DEFAULT_LOCATION_ARGUMENT);         }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 95 "3rd/iec61131.l"
{ return deci::parser_t::make_COPEN(DEFAULT_LOCATION_ARGUMENT);          }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 97 "3rd/iec61131.l"
{ return deci::parser_t::make_BOOLEAN(true,  DEFAULT_LOCATION_ARGUMENT); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 98 "3rd/iec61131.l"
{ return deci::parser_t::make_BOOLEAN(false, DEFAULT_LOCATION_ARGUMENT); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 99 "3rd/iec61131.l"
{ return deci::parser_t::make_BOOLEAN(true,  DEFAULT_LOCATION_ARGUMENT); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 100 "3rd/iec61131.l"
{ return deci::parser_t::make_BOOLEAN(false, DEFAULT_LOCATION_ARGUMENT); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 101 "3rd/iec61131.l"
{ return deci::parser_t::make_BOOLEAN(false, DEFAULT_LOCATION_ARGUMENT); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 102 "3rd/iec61131.l"
{ return deci::parser_t::make_BOOLEAN(true,  DEFAULT_LOCATION_ARGUMENT); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 104 "3rd/iec61131.l"
{
                        return deci::parser_t::make_NUMBER_STR(yytext, DEFAULT_LOCATION_ARGUMENT);
                     }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 108 "3rd/iec61131.l"
{
                        return deci::parser_t::make_IDENTIFIER(yytext, DEFAULT_LOCATION_ARGUMENT);
                     }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 112 "3rd/iec61131.l"
{
                        return deci::parser_t::make_NUMBER_STR(yytext, DEFAULT_LOCATION_ARGUMENT);
                     }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 116 "3rd/iec61131.l"
{
                        return deci::parser_t::make_NUMBER(atof(yytext), DEFAULT_LOCATION_ARGUMENT);
                     }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 120 "3rd/iec61131.l"
{
                        return deci::parser_t::make_NUMBER(atof(yytext), DEFAULT_LOCATION_ARGUMENT);
                     }
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 124 "3rd/iec61131.l"
{
                        if (this->interactive)
                        {
                          return deci::parser_t::make_END(DEFAULT_LOCATION_ARGUMENT);
                        }
                        else
                        {
                          this->cloc.lines();
                          this->cloc.step();
                        }
                     }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(DIV_COMMENTS):
case YY_STATE_EOF(BRACE_COMMENTS):
#line 136 "3rd/iec61131.l"
{
                        return deci::parser_t::make_END(DEFAULT_LOCATION_ARGUMENT);
                     }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 140 "3rd/iec61131.l"
{
                        // IGNORE SPACES;
                     }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 144 "3rd/iec61131.l"
{
                        throw deci::parser_t::syntax_error(DEFAULT_LOCATION_ARGUMENT, "未知的标识符");
                     }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 147 "3rd/iec61131.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1351 "3rd/iec61131.l.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin.rdbuf();
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* The contents of this function are C++ specific, so the () macro is not used.
 * This constructor simply maintains backward compatibility.
 * DEPRECATED
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout ):
	yyin(arg_yyin ? arg_yyin->rdbuf() : std::cin.rdbuf()),
	yyout(arg_yyout ? arg_yyout->rdbuf() : std::cout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream& arg_yyin, std::ostream& arg_yyout ):
	yyin(arg_yyin.rdbuf()),
	yyout(arg_yyout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::ctor_common()
{
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = NULL;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	yyfree( yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yyfree( yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream& new_in, std::ostream& new_out )
{
	// was if( new_in )
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );

	// was if( new_out )
	yyout.rdbuf(new_out.rdbuf());
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if( ! new_in ) {
		new_in = &yyin;
	}

	if ( ! new_out ) {
		new_out = &yyout;
	}

	switch_streams(*new_in, *new_out);
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin.eof() || yyin.fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin.get( buf[0] );

	if ( yyin.eof() )
		return 0;

	if ( yyin.bad() )
		return -1;

	return 1;

#else
	(void) yyin.read( buf, max_size );

	if ( yyin.bad() )
		return -1;
	else
		return yyin.gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout.write( buf, size );
}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
int yyFlexLexer::yy_get_next_buffer()
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    yy_state_type yyFlexLexer::yy_get_previous_state()
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 208 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 208 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 207);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
    void yyFlexLexer::yyunput( int c, char* yy_bp)
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
#endif

    int yyFlexLexer::yyinput()
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyFlexLexer::yyrestart( std::istream& input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Delegate to the new version that takes an istream reference.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
void yyFlexLexer::yyrestart( std::istream* input_file )
{
	if( ! input_file ) {
		input_file = &yyin;
	}
	yyrestart( *input_file );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

    void yyFlexLexer::yy_load_buffer_state()
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin.rdbuf(YY_CURRENT_BUFFER_LVALUE->yy_input_file);
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream& file, int size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Delegate creation of buffers to the new version that takes an istream reference.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
	YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
	return yy_create_buffer( *file, size );
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream& file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file.rdbuf();
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

	b->yy_is_interactive = 0;
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yyFlexLexer::yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
void yyFlexLexer::yyensure_buffer_stack(void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

    void yyFlexLexer::yy_push_state( int _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    void yyFlexLexer::yy_pop_state()
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    int yyFlexLexer::yy_top_state()
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

void yyFlexLexer::LexerError( const char* msg )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 147 "3rd/iec61131.l"


